version: '1.0'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: kaloom
      MONGO_INITDB_ROOT_PASSWORD: verySecure

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: kaloom
      ME_CONFIG_MONGODB_ADMINPASSWORD: verySecure
      ME_CONFIG_MONGODB_URL: mongodb://kaloom:verySecure@mongo:27017/